services:
    nodeapp:
        build: .
        restart: always
        ports:
            - 3000:3000
        expose:
            - 3000
        environment:
            HOST: "mysqldb"
            PORT: "3306"
            USER: "root"
            PASSWORD: "root"
        depends_on:
            - mysqldb

    mysqldb:
        volumes:
            - ./src/data:/var/lib/mysql
        restart: on-failure
        image: mysql:8.1
        ports:
            - 3307:3306
        expose:
            - 3306
        environment:
            MYSQL_PASSWORD: "root"
            MYSQL_ROOT_PASSWORD: "root"
