services:
    nodeapp:
        build: .
        restart: always
        ports:
            - 3000:3000
        expose:
            - 3000
        environment:
            HOST: "mysqldb"
            PORT: "3306"
            USER: "root"
            PASSWORD: "root"
        depends_on:
            mysqldb:
                condition: service_healthy

    mysqldb:
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 5s
            timeout: 5s
            retries: 10
        restart: on-failure
        image: mysql:8.1
        volumes:
            - db-data:/var/lib/mysql
        ports:
            - 3306:9306
        environment:
            MYSQL_PASSWORD: "root"
            MYSQL_ROOT_PASSWORD: "root"
volumes:
    db-data:
